// Achievement definitions for FunTime productivity app

export interface Achievement {
  id: string;
  name: string;
  description: string;
  icon: string;
  category: 'streak' | 'blocker' | 'journal' | 'panic' | 'special';
  requirement: number;
  unlockedAt: string | null;
  progress: number;
}

export const achievements: Achievement[] = [
  // ── Streak achievements ──────────────────────────────────────────────
  {
    id: 'first_day',
    name: 'First Step',
    description: 'Complete your first day',
    icon: 'footprints',
    category: 'streak',
    requirement: 1,
    unlockedAt: null,
    progress: 0,
  },
  {
    id: 'three_days',
    name: 'Getting Started',
    description: 'Maintain a 3-day streak',
    icon: 'flame',
    category: 'streak',
    requirement: 3,
    unlockedAt: null,
    progress: 0,
  },
  {
    id: 'week_warrior',
    name: 'Week Warrior',
    description: '7-day streak',
    icon: 'sword',
    category: 'streak',
    requirement: 7,
    unlockedAt: null,
    progress: 0,
  },
  {
    id: 'two_weeks',
    name: 'Fortnight Fighter',
    description: '14-day streak',
    icon: 'shield',
    category: 'streak',
    requirement: 14,
    unlockedAt: null,
    progress: 0,
  },
  {
    id: 'month_master',
    name: 'Month Master',
    description: '30-day streak',
    icon: 'crown',
    category: 'streak',
    requirement: 30,
    unlockedAt: null,
    progress: 0,
  },
  {
    id: 'sixty_days',
    name: 'Double Down',
    description: '60-day streak',
    icon: 'mountain',
    category: 'streak',
    requirement: 60,
    unlockedAt: null,
    progress: 0,
  },
  {
    id: 'ninety_days',
    name: 'Quarter Champion',
    description: '90-day streak — a true reboot',
    icon: 'trophy',
    category: 'streak',
    requirement: 90,
    unlockedAt: null,
    progress: 0,
  },
  {
    id: 'half_year',
    name: 'Half-Year Hero',
    description: '180-day streak',
    icon: 'star',
    category: 'streak',
    requirement: 180,
    unlockedAt: null,
    progress: 0,
  },
  {
    id: 'one_year',
    name: 'Legendary',
    description: '365-day streak — one full year',
    icon: 'gem',
    category: 'streak',
    requirement: 365,
    unlockedAt: null,
    progress: 0,
  },

  // ── Blocker achievements ─────────────────────────────────────────────
  {
    id: 'first_block',
    name: 'Shield Up',
    description: 'Enable your first block category',
    icon: 'shield-check',
    category: 'blocker',
    requirement: 1,
    unlockedAt: null,
    progress: 0,
  },
  {
    id: 'five_categories',
    name: 'Fortress Builder',
    description: 'Enable 5 block categories',
    icon: 'castle',
    category: 'blocker',
    requirement: 5,
    unlockedAt: null,
    progress: 0,
  },
  {
    id: 'all_categories',
    name: 'Total Lockdown',
    description: 'Enable all block categories at once',
    icon: 'lock',
    category: 'blocker',
    requirement: 7,
    unlockedAt: null,
    progress: 0,
  },
  {
    id: 'locked_block',
    name: 'Unbreakable',
    description: 'Lock a block category with a timer',
    icon: 'timer',
    category: 'blocker',
    requirement: 1,
    unlockedAt: null,
    progress: 0,
  },
  {
    id: 'block_week',
    name: 'Consistent Guard',
    description: 'Keep a blocker enabled for 7 consecutive days',
    icon: 'shield-alert',
    category: 'blocker',
    requirement: 7,
    unlockedAt: null,
    progress: 0,
  },

  // ── Journal achievements ─────────────────────────────────────────────
  {
    id: 'first_entry',
    name: 'Dear Diary',
    description: 'Write your first journal entry',
    icon: 'book-open',
    category: 'journal',
    requirement: 1,
    unlockedAt: null,
    progress: 0,
  },
  {
    id: 'ten_entries',
    name: 'Reflective Mind',
    description: 'Write 10 journal entries',
    icon: 'notebook-pen',
    category: 'journal',
    requirement: 10,
    unlockedAt: null,
    progress: 0,
  },
  {
    id: 'fifty_entries',
    name: 'Chronicler',
    description: 'Write 50 journal entries',
    icon: 'scroll-text',
    category: 'journal',
    requirement: 50,
    unlockedAt: null,
    progress: 0,
  },
  {
    id: 'journal_streak_7',
    name: 'Daily Writer',
    description: 'Write a journal entry 7 days in a row',
    icon: 'pencil-line',
    category: 'journal',
    requirement: 7,
    unlockedAt: null,
    progress: 0,
  },
  {
    id: 'journal_streak_30',
    name: 'Dedicated Author',
    description: 'Write a journal entry 30 days in a row',
    icon: 'feather',
    category: 'journal',
    requirement: 30,
    unlockedAt: null,
    progress: 0,
  },

  // ── Panic button achievements ────────────────────────────────────────
  {
    id: 'first_panic',
    name: 'Emergency Exit',
    description: 'Use the panic button for the first time',
    icon: 'siren',
    category: 'panic',
    requirement: 1,
    unlockedAt: null,
    progress: 0,
  },
  {
    id: 'panic_survivor',
    name: 'Urge Surfer',
    description: 'Use the panic button 10 times and keep your streak',
    icon: 'waves',
    category: 'panic',
    requirement: 10,
    unlockedAt: null,
    progress: 0,
  },
  {
    id: 'panic_master',
    name: 'Calm in the Storm',
    description: 'Use the panic button 25 times without breaking streak',
    icon: 'cloud-sun',
    category: 'panic',
    requirement: 25,
    unlockedAt: null,
    progress: 0,
  },

  // ── Special achievements ─────────────────────────────────────────────
  {
    id: 'night_owl',
    name: 'Night Owl',
    description: 'Open the app between midnight and 5 AM and stay strong',
    icon: 'moon',
    category: 'special',
    requirement: 1,
    unlockedAt: null,
    progress: 0,
  },
  {
    id: 'early_bird',
    name: 'Early Bird',
    description: 'Open the app before 6 AM',
    icon: 'sunrise',
    category: 'special',
    requirement: 1,
    unlockedAt: null,
    progress: 0,
  },
  {
    id: 'comeback_kid',
    name: 'Comeback Kid',
    description: 'Start a new streak after a reset',
    icon: 'rotate-ccw',
    category: 'special',
    requirement: 1,
    unlockedAt: null,
    progress: 0,
  },
];
