// Domain blocklists by category for FunTime productivity app
// Used by the content blocker to prevent access to distracting or harmful sites.

export interface BlocklistCategory {
  domains: string[];
}

export const blocklists: Record<string, BlocklistCategory> = {
  // ── Adult / Pornographic sites (150+) ────────────────────────────────
  adult: {
    domains: [
      'pornhub.com',
      'xvideos.com',
      'xhamster.com',
      'redtube.com',
      'youporn.com',
      'xnxx.com',
      'tube8.com',
      'spankbang.com',
      'beeg.com',
      'brazzers.com',
      'naughtyamerica.com',
      'realitykings.com',
      'bangbros.com',
      'mofos.com',
      'digitalplayground.com',
      'babes.com',
      'twistys.com',
      'wicked.com',
      'evilangel.com',
      'kink.com',
      'chaturbate.com',
      'stripchat.com',
      'bongacams.com',
      'cam4.com',
      'myfreecams.com',
      'livejasmin.com',
      'camsoda.com',
      'flirt4free.com',
      'streamate.com',
      'imlive.com',
      'porntrex.com',
      'tnaflix.com',
      'drtuber.com',
      'txxx.com',
      'hclips.com',
      'voyeurhit.com',
      'sunporno.com',
      'anyporn.com',
      'bravotube.net',
      'empflix.com',
      'tubegalore.com',
      'alohatube.com',
      'fuq.com',
      'thumbzilla.com',
      'porntube.com',
      'pornone.com',
      'fapvid.com',
      'sxyprn.com',
      'daftsex.com',
      'hqporner.com',
      'eporner.com',
      'pornpics.com',
      'imagefap.com',
      'motherless.com',
      'heavy-r.com',
      'efukt.com',
      'vporn.com',
      'porndig.com',
      'bellesa.co',
      'hegre.com',
      'metart.com',
      'suicidegirls.com',
      'playboy.com',
      'penthouse.com',
      'hustler.com',
      'onlyfans.com',
      'fansly.com',
      'manyvids.com',
      'clips4sale.com',
      'iwantclips.com',
      'loyalfans.com',
      'justforfans.com',
      'porngo.com',
      'youjizz.com',
      'jizzbunker.com',
      'pornhd.com',
      'perfectgirls.net',
      'porn.com',
      'sex.com',
      'literotica.com',
      'rule34.xxx',
      'e-hentai.org',
      'nhentai.net',
      'hentaihaven.xxx',
      'hanime.tv',
      'gelbooru.com',
      'danbooru.donmai.us',
      'sankakucomplex.com',
      'konachan.com',
      'hitomi.la',
      'tsumino.com',
      'simply-hentai.com',
      'fakku.net',
      'doujins.com',
      'noodlemagazine.com',
      'sextube.com',
      'pornmd.com',
      'pornhits.com',
      'nudevista.com',
      'lobstertube.com',
      'fux.com',
      'pornrox.com',
      'porn300.com',
      'fapster.xxx',
      'porndoe.com',
      'amateur8.com',
      'pornoxo.com',
      'pornhat.com',
      'fullporner.com',
      'fapcat.com',
      'ashemaletube.com',
      'trannytube.tv',
      'femjoyhunter.com',
      'theporndude.com',
      'ixxx.com',
      'al4a.com',
      'silverdaddies.com',
      'adam4adam.com',
      'gaymaletube.com',
      'boyfriendtv.com',
      'gaytube.com',
      'cam.com',
      'rabbits.webcam',
      'camster.com',
      'xcams.com',
      'slutroulette.com',
      'dirtyroulette.com',
      'omegle.com',
      'chatrandom.com',
      'camfrog.com',
      'flingster.com',
      'shagle.com',
      'chatroulette.com',
      'mydirtyhobby.com',
      'xpee.com',
      'analdin.com',
      'gotporn.com',
      'megatube.xxx',
      'xbabe.com',
      'xxxbunker.com',
      'zbporn.com',
      'proporn.com',
      'tubedupe.com',
      'hdzog.com',
      'hotmovs.com',
      'upornia.com',
      'hdporncomics.com',
      '3movs.com',
      'porndish.com',
      'freeones.com',
      'iafd.com',
      'indexxx.com',
      'adultempire.com',
      'gamelink.com',
      'aebn.com',
    ],
  },

  // ── Social Media (30+) ──────────────────────────────────────────────
  social_media: {
    domains: [
      'twitter.com',
      'x.com',
      'facebook.com',
      'instagram.com',
      'tiktok.com',
      'reddit.com',
      'snapchat.com',
      'pinterest.com',
      'linkedin.com',
      'tumblr.com',
      'discord.com',
      'telegram.org',
      'web.telegram.org',
      'whatsapp.com',
      'web.whatsapp.com',
      'threads.net',
      'mastodon.social',
      'bsky.app',
      'truthsocial.com',
      'gettr.com',
      'parler.com',
      'gab.com',
      'minds.com',
      'mewe.com',
      'vk.com',
      'weibo.com',
      'line.me',
      'kakaotalk.com',
      'signal.org',
      'clubhouse.com',
      'quora.com',
      'lemon8-app.com',
      'bereal.com',
    ],
  },

  // ── Gambling (20+) ──────────────────────────────────────────────────
  gambling: {
    domains: [
      'bet365.com',
      'draftkings.com',
      'fanduel.com',
      'betmgm.com',
      'caesars.com',
      'pointsbet.com',
      'williamhill.com',
      'betway.com',
      'unibet.com',
      '888sport.com',
      'pokerstars.com',
      'partypoker.com',
      'bovada.lv',
      'betonline.ag',
      'mybookie.ag',
      'stake.com',
      'roobet.com',
      'duelbits.com',
      'rollbit.com',
      'betrivers.com',
      'wynnbet.com',
      'twinspires.com',
      'betus.com.pa',
      'sportsbetting.ag',
    ],
  },

  // ── News (20+) ──────────────────────────────────────────────────────
  news: {
    domains: [
      'cnn.com',
      'foxnews.com',
      'msnbc.com',
      'bbc.com',
      'bbc.co.uk',
      'nytimes.com',
      'washingtonpost.com',
      'theguardian.com',
      'reuters.com',
      'apnews.com',
      'nbcnews.com',
      'abcnews.go.com',
      'cbsnews.com',
      'usatoday.com',
      'huffpost.com',
      'buzzfeednews.com',
      'dailymail.co.uk',
      'nypost.com',
      'politico.com',
      'thehill.com',
      'axios.com',
      'vox.com',
      'vice.com',
      'newsweek.com',
    ],
  },

  // ── Entertainment (15+) ─────────────────────────────────────────────
  entertainment: {
    domains: [
      'youtube.com',
      'netflix.com',
      'twitch.tv',
      'hulu.com',
      'disneyplus.com',
      'hbomax.com',
      'max.com',
      'peacocktv.com',
      'paramountplus.com',
      'crunchyroll.com',
      'funimation.com',
      'dailymotion.com',
      'vimeo.com',
      'rumble.com',
      'bitchute.com',
      'odysee.com',
      'kick.com',
      'pluto.tv',
      'tubi.tv',
    ],
  },

  // ── Gaming (15+) ────────────────────────────────────────────────────
  gaming: {
    domains: [
      'store.steampowered.com',
      'steampowered.com',
      'epicgames.com',
      'gog.com',
      'ea.com',
      'origin.com',
      'battle.net',
      'ubisoft.com',
      'roblox.com',
      'minecraft.net',
      'leagueoflegends.com',
      'playstation.com',
      'xbox.com',
      'nintendo.com',
      'itch.io',
      'humble.com',
      'g2a.com',
      'cdkeys.com',
      'greenmangaming.com',
    ],
  },

  // ── Shopping (12+) ──────────────────────────────────────────────────
  shopping: {
    domains: [
      'amazon.com',
      'ebay.com',
      'walmart.com',
      'target.com',
      'bestbuy.com',
      'etsy.com',
      'aliexpress.com',
      'wish.com',
      'shein.com',
      'temu.com',
      'wayfair.com',
      'overstock.com',
      'newegg.com',
      'zappos.com',
      'asos.com',
    ],
  },
};
