// Motivational quotes for FunTime productivity app
// 100+ quotes across motivation, discipline, recovery, and productivity categories.

export interface Quote {
  id: number;
  text: string;
  author: string;
  category: 'motivation' | 'discipline' | 'recovery' | 'productivity';
}

export const quotes: Quote[] = [
  // ── MOTIVATION (1–30) ────────────────────────────────────────────────
  {
    id: 1,
    text: 'The secret of getting ahead is getting started.',
    author: 'Mark Twain',
    category: 'motivation',
  },
  {
    id: 2,
    text: 'It does not matter how slowly you go as long as you do not stop.',
    author: 'Confucius',
    category: 'motivation',
  },
  {
    id: 3,
    text: 'The impediment to action advances action. What stands in the way becomes the way.',
    author: 'Marcus Aurelius',
    category: 'motivation',
  },
  {
    id: 4,
    text: 'You have power over your mind — not outside events. Realize this, and you will find strength.',
    author: 'Marcus Aurelius',
    category: 'motivation',
  },
  {
    id: 5,
    text: 'The best time to plant a tree was 20 years ago. The second best time is now.',
    author: 'Chinese Proverb',
    category: 'motivation',
  },
  {
    id: 6,
    text: "Believe you can and you're halfway there.",
    author: 'Theodore Roosevelt',
    category: 'motivation',
  },
  {
    id: 7,
    text: 'What we achieve inwardly will change outer reality.',
    author: 'Plutarch',
    category: 'motivation',
  },
  {
    id: 8,
    text: "Don't let yesterday take up too much of today.",
    author: 'Will Rogers',
    category: 'motivation',
  },
  {
    id: 9,
    text: 'Be tolerant with others and strict with yourself.',
    author: 'Marcus Aurelius',
    category: 'motivation',
  },
  {
    id: 10,
    text: 'The only way to do great work is to love what you do.',
    author: 'Steve Jobs',
    category: 'motivation',
  },
  {
    id: 11,
    text: 'A man who conquers himself is greater than one who conquers a thousand men in battle.',
    author: 'Buddha',
    category: 'motivation',
  },
  {
    id: 12,
    text: 'Our greatest glory is not in never falling, but in rising every time we fall.',
    author: 'Confucius',
    category: 'motivation',
  },
  {
    id: 13,
    text: 'The man who moves a mountain begins by carrying away small stones.',
    author: 'Confucius',
    category: 'motivation',
  },
  {
    id: 14,
    text: 'Strength does not come from physical capacity. It comes from an indomitable will.',
    author: 'Mahatma Gandhi',
    category: 'motivation',
  },
  {
    id: 15,
    text: 'No man is free who is not master of himself.',
    author: 'Epictetus',
    category: 'motivation',
  },
  {
    id: 16,
    text: 'The only person you are destined to become is the person you decide to be.',
    author: 'Ralph Waldo Emerson',
    category: 'motivation',
  },
  {
    id: 17,
    text: "Hard times don't create heroes. It is during the hard times when the hero within us is revealed.",
    author: 'Bob Riley',
    category: 'motivation',
  },
  {
    id: 18,
    text: 'The mind is everything. What you think you become.',
    author: 'Buddha',
    category: 'motivation',
  },
  {
    id: 19,
    text: "If you're going through hell, keep going.",
    author: 'Winston Churchill',
    category: 'motivation',
  },
  {
    id: 20,
    text: "Courage isn't having the strength to go on — it is going on when you don't have strength.",
    author: 'Napoleon Bonaparte',
    category: 'motivation',
  },
  {
    id: 21,
    text: 'Do not pray for an easy life; pray for the strength to endure a difficult one.',
    author: 'Bruce Lee',
    category: 'motivation',
  },
  {
    id: 22,
    text: 'You are braver than you believe, stronger than you seem, and smarter than you think.',
    author: 'A.A. Milne',
    category: 'motivation',
  },
  {
    id: 23,
    text: 'He who has a why to live can bear almost any how.',
    author: 'Friedrich Nietzsche',
    category: 'motivation',
  },
  {
    id: 24,
    text: 'Success is not final, failure is not fatal: it is the courage to continue that counts.',
    author: 'Winston Churchill',
    category: 'motivation',
  },
  {
    id: 25,
    text: 'Everything you want is on the other side of fear.',
    author: 'Jack Canfield',
    category: 'motivation',
  },
  {
    id: 26,
    text: 'The greatest wealth is to live content with little.',
    author: 'Plato',
    category: 'motivation',
  },
  {
    id: 27,
    text: 'What you do today can improve all your tomorrows.',
    author: 'Ralph Marston',
    category: 'motivation',
  },
  {
    id: 28,
    text: 'You miss 100% of the shots you don\'t take.',
    author: 'Wayne Gretzky',
    category: 'motivation',
  },
  {
    id: 29,
    text: 'Act as if what you do makes a difference. It does.',
    author: 'William James',
    category: 'motivation',
  },
  {
    id: 30,
    text: 'The wound is the place where the Light enters you.',
    author: 'Rumi',
    category: 'motivation',
  },

  // ── DISCIPLINE (31–60) ───────────────────────────────────────────────
  {
    id: 31,
    text: 'Discipline equals freedom.',
    author: 'Jocko Willink',
    category: 'discipline',
  },
  {
    id: 32,
    text: "Don't expect to be motivated every day. You have to be disciplined.",
    author: 'Jocko Willink',
    category: 'discipline',
  },
  {
    id: 33,
    text: 'Good. Get after it.',
    author: 'Jocko Willink',
    category: 'discipline',
  },
  {
    id: 34,
    text: 'The more you sweat in training, the less you bleed in combat.',
    author: 'Jocko Willink',
    category: 'discipline',
  },
  {
    id: 35,
    text: "Suffer the pain of discipline or suffer the pain of regret. You can't have both.",
    author: 'David Goggins',
    category: 'discipline',
  },
  {
    id: 36,
    text: "You're in danger of living a life so comfortable and soft that you will die without ever realizing your potential.",
    author: 'David Goggins',
    category: 'discipline',
  },
  {
    id: 37,
    text: 'The only thing more contagious than a good attitude is a disciplined one.',
    author: 'David Goggins',
    category: 'discipline',
  },
  {
    id: 38,
    text: "When you think you're done, you're only at 40% of your body's actual capability.",
    author: 'David Goggins',
    category: 'discipline',
  },
  {
    id: 39,
    text: 'We suffer more in imagination than in reality.',
    author: 'Seneca',
    category: 'discipline',
  },
  {
    id: 40,
    text: 'It is not that we have a short time to live, but that we waste a great deal of it.',
    author: 'Seneca',
    category: 'discipline',
  },
  {
    id: 41,
    text: 'Luck is what happens when preparation meets opportunity.',
    author: 'Seneca',
    category: 'discipline',
  },
  {
    id: 42,
    text: 'He who is brave is free.',
    author: 'Seneca',
    category: 'discipline',
  },
  {
    id: 43,
    text: 'Difficulties strengthen the mind as labor does the body.',
    author: 'Seneca',
    category: 'discipline',
  },
  {
    id: 44,
    text: 'No great thing is created suddenly.',
    author: 'Epictetus',
    category: 'discipline',
  },
  {
    id: 45,
    text: 'First say to yourself what you would be; and then do what you have to do.',
    author: 'Epictetus',
    category: 'discipline',
  },
  {
    id: 46,
    text: 'The chief task in life is simply this: to identify and separate matters so that I can say clearly to myself which are externals not under my control, and which have to do with the choices I actually control.',
    author: 'Epictetus',
    category: 'discipline',
  },
  {
    id: 47,
    text: 'With self-discipline most anything is possible.',
    author: 'Theodore Roosevelt',
    category: 'discipline',
  },
  {
    id: 48,
    text: 'Rule your mind or it will rule you.',
    author: 'Horace',
    category: 'discipline',
  },
  {
    id: 49,
    text: 'Self-control is strength. Right thought is mastery. Calmness is power.',
    author: 'James Allen',
    category: 'discipline',
  },
  {
    id: 50,
    text: 'Mastering others is strength. Mastering yourself is true power.',
    author: 'Lao Tzu',
    category: 'discipline',
  },
  {
    id: 51,
    text: 'The chains of habit are too light to be felt until they are too heavy to be broken.',
    author: 'Samuel Johnson',
    category: 'discipline',
  },
  {
    id: 52,
    text: 'Motivation gets you going, but discipline keeps you growing.',
    author: 'John C. Maxwell',
    category: 'discipline',
  },
  {
    id: 53,
    text: 'Hold yourself responsible for a higher standard than anyone else expects of you.',
    author: 'Henry Ward Beecher',
    category: 'discipline',
  },
  {
    id: 54,
    text: 'We must all suffer one of two things: the pain of discipline or the pain of regret.',
    author: 'Jim Rohn',
    category: 'discipline',
  },
  {
    id: 55,
    text: 'Your ego is not your amigo.',
    author: 'Jocko Willink',
    category: 'discipline',
  },
  {
    id: 56,
    text: 'Waste no more time arguing about what a good man should be. Be one.',
    author: 'Marcus Aurelius',
    category: 'discipline',
  },
  {
    id: 57,
    text: 'The happiness of your life depends upon the quality of your thoughts.',
    author: 'Marcus Aurelius',
    category: 'discipline',
  },
  {
    id: 58,
    text: 'How long are you going to wait before you demand the best for yourself?',
    author: 'Epictetus',
    category: 'discipline',
  },
  {
    id: 59,
    text: 'A gem cannot be polished without friction, nor a man perfected without trials.',
    author: 'Seneca',
    category: 'discipline',
  },
  {
    id: 60,
    text: 'The only discipline that lasts is self-discipline.',
    author: 'Bum Phillips',
    category: 'discipline',
  },

  // ── RECOVERY (61–85) ─────────────────────────────────────────────────
  {
    id: 61,
    text: 'Fall seven times, stand up eight.',
    author: 'Japanese Proverb',
    category: 'recovery',
  },
  {
    id: 62,
    text: 'A relapse is not the end of recovery. It is part of recovery.',
    author: 'Unknown',
    category: 'recovery',
  },
  {
    id: 63,
    text: 'Every morning we are born again. What we do today matters most.',
    author: 'Buddha',
    category: 'recovery',
  },
  {
    id: 64,
    text: 'Rock bottom became the solid foundation on which I rebuilt my life.',
    author: 'J.K. Rowling',
    category: 'recovery',
  },
  {
    id: 65,
    text: "It's not about being perfect. It's about effort. When you bring that effort every day, that's where transformation happens.",
    author: 'Jillian Michaels',
    category: 'recovery',
  },
  {
    id: 66,
    text: 'One day at a time. One step at a time.',
    author: 'Unknown',
    category: 'recovery',
  },
  {
    id: 67,
    text: 'The comeback is always stronger than the setback.',
    author: 'Unknown',
    category: 'recovery',
  },
  {
    id: 68,
    text: 'Recovery is not a race. You do not have to feel guilty if it takes you longer than you thought it would.',
    author: 'Unknown',
    category: 'recovery',
  },
  {
    id: 69,
    text: 'You are not defined by your past. You are prepared by it.',
    author: 'Unknown',
    category: 'recovery',
  },
  {
    id: 70,
    text: 'The strongest people are not those who show strength in front of us, but those who win battles we know nothing about.',
    author: 'Unknown',
    category: 'recovery',
  },
  {
    id: 71,
    text: 'Healing is not linear.',
    author: 'Unknown',
    category: 'recovery',
  },
  {
    id: 72,
    text: 'The first step towards getting somewhere is to decide you are not going to stay where you are.',
    author: 'J.P. Morgan',
    category: 'recovery',
  },
  {
    id: 73,
    text: 'Tough times never last, but tough people do.',
    author: 'Robert H. Schuller',
    category: 'recovery',
  },
  {
    id: 74,
    text: "I am not what happened to me. I am what I choose to become.",
    author: 'Carl Jung',
    category: 'recovery',
  },
  {
    id: 75,
    text: 'Turn your wounds into wisdom.',
    author: 'Oprah Winfrey',
    category: 'recovery',
  },
  {
    id: 76,
    text: "Out of suffering have emerged the strongest souls; the most massive characters are seared with scars.",
    author: 'Khalil Gibran',
    category: 'recovery',
  },
  {
    id: 77,
    text: 'You may have to fight a battle more than once to win it.',
    author: 'Margaret Thatcher',
    category: 'recovery',
  },
  {
    id: 78,
    text: 'The greatest glory in living lies not in never falling, but in rising every time we fall.',
    author: 'Nelson Mandela',
    category: 'recovery',
  },
  {
    id: 79,
    text: 'What lies behind us and what lies before us are tiny matters compared to what lies within us.',
    author: 'Ralph Waldo Emerson',
    category: 'recovery',
  },
  {
    id: 80,
    text: 'When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.',
    author: 'Henry Ford',
    category: 'recovery',
  },
  {
    id: 81,
    text: 'Promise me you will not spend so much time treading water and trying to keep your head above the waves that you forget, truly forget, how much you have always loved to swim.',
    author: 'Tyler Knott Gregson',
    category: 'recovery',
  },
  {
    id: 82,
    text: 'Every saint has a past, and every sinner has a future.',
    author: 'Oscar Wilde',
    category: 'recovery',
  },
  {
    id: 83,
    text: 'Recovery is about progression, not perfection.',
    author: 'Unknown',
    category: 'recovery',
  },
  {
    id: 84,
    text: 'Forgive yourself for not knowing what you did not know before you learned it.',
    author: 'Doe Zantamata',
    category: 'recovery',
  },
  {
    id: 85,
    text: 'Stars can not shine without darkness.',
    author: 'D.H. Sidebottom',
    category: 'recovery',
  },

  // ── PRODUCTIVITY (86–110) ────────────────────────────────────────────
  {
    id: 86,
    text: 'Free education is abundant, all over the internet. It is the desire to learn that is scarce.',
    author: 'Naval Ravikant',
    category: 'productivity',
  },
  {
    id: 87,
    text: 'If you can not decide, the answer is no.',
    author: 'Naval Ravikant',
    category: 'productivity',
  },
  {
    id: 88,
    text: 'The modern struggle: feeling the urge to distract yourself the moment anything gets slightly difficult.',
    author: 'Naval Ravikant',
    category: 'productivity',
  },
  {
    id: 89,
    text: 'Seek wealth, not money or status. Wealth is having assets that earn while you sleep.',
    author: 'Naval Ravikant',
    category: 'productivity',
  },
  {
    id: 90,
    text: 'Play long-term games with long-term people.',
    author: 'Naval Ravikant',
    category: 'productivity',
  },
  {
    id: 91,
    text: 'An investment in knowledge pays the best interest.',
    author: 'Benjamin Franklin',
    category: 'productivity',
  },
  {
    id: 92,
    text: 'The way to get started is to quit talking and begin doing.',
    author: 'Walt Disney',
    category: 'productivity',
  },
  {
    id: 93,
    text: "Don't count the days, make the days count.",
    author: 'Muhammad Ali',
    category: 'productivity',
  },
  {
    id: 94,
    text: 'Focus on being productive instead of busy.',
    author: 'Tim Ferriss',
    category: 'productivity',
  },
  {
    id: 95,
    text: 'What gets measured gets managed.',
    author: 'Peter Drucker',
    category: 'productivity',
  },
  {
    id: 96,
    text: 'Productivity is never an accident. It is always the result of a commitment to excellence, intelligent planning, and focused effort.',
    author: 'Paul J. Meyer',
    category: 'productivity',
  },
  {
    id: 97,
    text: 'Time is what we want most but what we use worst.',
    author: 'William Penn',
    category: 'productivity',
  },
  {
    id: 98,
    text: 'The key is not to prioritize what is on your schedule, but to schedule your priorities.',
    author: 'Stephen Covey',
    category: 'productivity',
  },
  {
    id: 99,
    text: "Your net worth to the world is usually determined by what remains after your bad habits are subtracted from your good ones.",
    author: 'Benjamin Franklin',
    category: 'productivity',
  },
  {
    id: 100,
    text: 'Either you run the day or the day runs you.',
    author: 'Jim Rohn',
    category: 'productivity',
  },
  {
    id: 101,
    text: 'Ordinary people think merely of spending time; great people think of using it.',
    author: 'Arthur Schopenhauer',
    category: 'productivity',
  },
  {
    id: 102,
    text: 'Until we can manage time, we can manage nothing else.',
    author: 'Peter Drucker',
    category: 'productivity',
  },
  {
    id: 103,
    text: 'The bad news is time flies. The good news is you are the pilot.',
    author: 'Michael Altshuler',
    category: 'productivity',
  },
  {
    id: 104,
    text: 'Action is the foundational key to all success.',
    author: 'Pablo Picasso',
    category: 'productivity',
  },
  {
    id: 105,
    text: 'Do not wait to strike till the iron is hot, but make it hot by striking.',
    author: 'William Butler Yeats',
    category: 'productivity',
  },
  {
    id: 106,
    text: 'You do not rise to the level of your goals. You fall to the level of your systems.',
    author: 'James Clear',
    category: 'productivity',
  },
  {
    id: 107,
    text: 'Habits are the compound interest of self-improvement.',
    author: 'James Clear',
    category: 'productivity',
  },
  {
    id: 108,
    text: 'Every action you take is a vote for the type of person you wish to become.',
    author: 'James Clear',
    category: 'productivity',
  },
  {
    id: 109,
    text: 'The most dangerous distractions are the ones you love, but that do not love you back.',
    author: 'Naval Ravikant',
    category: 'productivity',
  },
  {
    id: 110,
    text: 'Your mind is for having ideas, not holding them.',
    author: 'David Allen',
    category: 'productivity',
  },
];
